package org.luojj.dao;

import org.luojj.entity.BankCard;

public interface BankCardDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_card_number_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String phoneNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_card_number_info
     *
     * @mbggenerated
     */
    int insert(BankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_card_number_info
     *
     * @mbggenerated
     */
    int insertSelective(BankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_card_number_info
     *
     * @mbggenerated
     */
    BankCard selectByPrimaryKey(String phoneNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_card_number_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_card_number_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BankCard record);
}