package org.luojj.dao;

import org.luojj.entity.InvestmentStyleFactor;



public interface InvestmentStyleFactorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table investment_style_factor
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String phoneNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table investment_style_factor
     *
     * @mbggenerated
     */
    int insert(InvestmentStyleFactor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table investment_style_factor
     *
     * @mbggenerated
     */
    int insertSelective(InvestmentStyleFactor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table investment_style_factor
     *
     * @mbggenerated
     */
    InvestmentStyleFactor selectByPrimaryKey(String phoneNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table investment_style_factor
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(InvestmentStyleFactor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table investment_style_factor
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InvestmentStyleFactor record);
}