package org.luojj.entity;

import java.math.BigDecimal;
import java.util.Date;

import org.luojj.baseclass.BaseBean;

public class Asset extends BaseBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_info.phone_number
     *
     * @mbggenerated
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_info.balance
     *
     * @mbggenerated
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_info.total_asset
     *
     * @mbggenerated
     */
    private BigDecimal totalAsset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_info.yesterday_profit
     *
     * @mbggenerated
     */
    private BigDecimal yesterdayProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_info.total_profit
     *
     * @mbggenerated
     */
    private BigDecimal totalProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_info.phone_number
     *
     * @return the value of asset_info.phone_number
     *
     * @mbggenerated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_info.phone_number
     *
     * @param phoneNumber the value for asset_info.phone_number
     *
     * @mbggenerated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_info.balance
     *
     * @return the value of asset_info.balance
     *
     * @mbggenerated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_info.balance
     *
     * @param balance the value for asset_info.balance
     *
     * @mbggenerated
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_info.total_asset
     *
     * @return the value of asset_info.total_asset
     *
     * @mbggenerated
     */
    public BigDecimal getTotalAsset() {
        return totalAsset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_info.total_asset
     *
     * @param totalAsset the value for asset_info.total_asset
     *
     * @mbggenerated
     */
    public void setTotalAsset(BigDecimal totalAsset) {
        this.totalAsset = totalAsset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_info.yesterday_profit
     *
     * @return the value of asset_info.yesterday_profit
     *
     * @mbggenerated
     */
    public BigDecimal getYesterdayProfit() {
        return yesterdayProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_info.yesterday_profit
     *
     * @param yesterdayProfit the value for asset_info.yesterday_profit
     *
     * @mbggenerated
     */
    public void setYesterdayProfit(BigDecimal yesterdayProfit) {
        this.yesterdayProfit = yesterdayProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_info.total_profit
     *
     * @return the value of asset_info.total_profit
     *
     * @mbggenerated
     */
    public BigDecimal getTotalProfit() {
        return totalProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_info.total_profit
     *
     * @param totalProfit the value for asset_info.total_profit
     *
     * @mbggenerated
     */
    public void setTotalProfit(BigDecimal totalProfit) {
        this.totalProfit = totalProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_info.create_time
     *
     * @return the value of asset_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_info.create_time
     *
     * @param createTime the value for asset_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}