package org.luojj.entity;

import java.util.Date;

import org.luojj.baseclass.BasicObject;

public class BankCard extends BasicObject{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_card_number_info.phone_number
     *
     * @mbggenerated
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_card_number_info.bank_card_number
     *
     * @mbggenerated
     */
    private String bankCardNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_card_number_info.bank_card_type
     *
     * @mbggenerated
     */
    private String bankCardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_card_number_info.bank_phone_number
     *
     * @mbggenerated
     */
    private String bankPhoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_card_number_info.bank_name
     *
     * @mbggenerated
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_card_number_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_card_number_info.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card_number_info.phone_number
     *
     * @return the value of bank_card_number_info.phone_number
     *
     * @mbggenerated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

	public String getBankCardNumber() {
		return bankCardNumber;
	}

	public void setBankCardNumber(String bankCardNumber) {
		this.bankCardNumber = bankCardNumber;
	}

	public String getBankCardType() {
		return bankCardType;
	}

	public void setBankCardType(String bankCardType) {
		this.bankCardType = bankCardType;
	}

	public String getBankPhoneNumber() {
		return bankPhoneNumber;
	}

	public void setBankPhoneNumber(String bankPhoneNumber) {
		this.bankPhoneNumber = bankPhoneNumber;
	}

	public String getBankName() {
		return bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getRealName() {
		return realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card_number_info.phone_number
     *
     * @param phoneNumber the value for bank_card_number_info.phone_number
     *
     * @mbggenerated
     */
    
}