package org.luojj.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Bond {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.product_id
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.bond_id
     *
     * @mbggenerated
     */
    private Integer bondId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.bond_name
     *
     * @mbggenerated
     */
    private String bondName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.bond_type
     *
     * @mbggenerated
     */
    private String bondType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.bond_price
     *
     * @mbggenerated
     */
    private BigDecimal bondPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.change_rate
     *
     * @mbggenerated
     */
    private BigDecimal changeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.change_price
     *
     * @mbggenerated
     */
    private BigDecimal changePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.invest_rate
     *
     * @mbggenerated
     */
    private BigDecimal investRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.buy_base
     *
     * @mbggenerated
     */
    private Integer buyBase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.risk_grade
     *
     * @mbggenerated
     */
    private String riskGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.buy_rate
     *
     * @mbggenerated
     */
    private BigDecimal buyRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.sell_rate
     *
     * @mbggenerated
     */
    private BigDecimal sellRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.product_id
     *
     * @return the value of bond_info.product_id
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.product_id
     *
     * @param productId the value for bond_info.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.bond_id
     *
     * @return the value of bond_info.bond_id
     *
     * @mbggenerated
     */
    public Integer getBondId() {
        return bondId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.bond_id
     *
     * @param bondId the value for bond_info.bond_id
     *
     * @mbggenerated
     */
    public void setBondId(Integer bondId) {
        this.bondId = bondId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.bond_name
     *
     * @return the value of bond_info.bond_name
     *
     * @mbggenerated
     */
    public String getBondName() {
        return bondName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.bond_name
     *
     * @param bondName the value for bond_info.bond_name
     *
     * @mbggenerated
     */
    public void setBondName(String bondName) {
        this.bondName = bondName == null ? null : bondName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.bond_type
     *
     * @return the value of bond_info.bond_type
     *
     * @mbggenerated
     */
    public String getBondType() {
        return bondType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.bond_type
     *
     * @param bondType the value for bond_info.bond_type
     *
     * @mbggenerated
     */
    public void setBondType(String bondType) {
        this.bondType = bondType == null ? null : bondType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.bond_price
     *
     * @return the value of bond_info.bond_price
     *
     * @mbggenerated
     */
    public BigDecimal getBondPrice() {
        return bondPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.bond_price
     *
     * @param bondPrice the value for bond_info.bond_price
     *
     * @mbggenerated
     */
    public void setBondPrice(BigDecimal bondPrice) {
        this.bondPrice = bondPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.change_rate
     *
     * @return the value of bond_info.change_rate
     *
     * @mbggenerated
     */
    public BigDecimal getChangeRate() {
        return changeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.change_rate
     *
     * @param changeRate the value for bond_info.change_rate
     *
     * @mbggenerated
     */
    public void setChangeRate(BigDecimal changeRate) {
        this.changeRate = changeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.change_price
     *
     * @return the value of bond_info.change_price
     *
     * @mbggenerated
     */
    public BigDecimal getChangePrice() {
        return changePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.change_price
     *
     * @param changePrice the value for bond_info.change_price
     *
     * @mbggenerated
     */
    public void setChangePrice(BigDecimal changePrice) {
        this.changePrice = changePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.invest_rate
     *
     * @return the value of bond_info.invest_rate
     *
     * @mbggenerated
     */
    public BigDecimal getInvestRate() {
        return investRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.invest_rate
     *
     * @param investRate the value for bond_info.invest_rate
     *
     * @mbggenerated
     */
    public void setInvestRate(BigDecimal investRate) {
        this.investRate = investRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.buy_base
     *
     * @return the value of bond_info.buy_base
     *
     * @mbggenerated
     */
    public Integer getBuyBase() {
        return buyBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.buy_base
     *
     * @param buyBase the value for bond_info.buy_base
     *
     * @mbggenerated
     */
    public void setBuyBase(Integer buyBase) {
        this.buyBase = buyBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.risk_grade
     *
     * @return the value of bond_info.risk_grade
     *
     * @mbggenerated
     */
    public String getRiskGrade() {
        return riskGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.risk_grade
     *
     * @param riskGrade the value for bond_info.risk_grade
     *
     * @mbggenerated
     */
    public void setRiskGrade(String riskGrade) {
        this.riskGrade = riskGrade == null ? null : riskGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.buy_rate
     *
     * @return the value of bond_info.buy_rate
     *
     * @mbggenerated
     */
    public BigDecimal getBuyRate() {
        return buyRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.buy_rate
     *
     * @param buyRate the value for bond_info.buy_rate
     *
     * @mbggenerated
     */
    public void setBuyRate(BigDecimal buyRate) {
        this.buyRate = buyRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.sell_rate
     *
     * @return the value of bond_info.sell_rate
     *
     * @mbggenerated
     */
    public BigDecimal getSellRate() {
        return sellRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.sell_rate
     *
     * @param sellRate the value for bond_info.sell_rate
     *
     * @mbggenerated
     */
    public void setSellRate(BigDecimal sellRate) {
        this.sellRate = sellRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.update_time
     *
     * @return the value of bond_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.update_time
     *
     * @param updateTime the value for bond_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.create_time
     *
     * @return the value of bond_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.create_time
     *
     * @param createTime the value for bond_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}