package org.luojj.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Fund {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.product_id
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.fund_id
     *
     * @mbggenerated
     */
    private Long fundId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.fund_name
     *
     * @mbggenerated
     */
    private String fundName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.change_rate
     *
     * @mbggenerated
     */
    private BigDecimal changeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.change_price
     *
     * @mbggenerated
     */
    private BigDecimal changePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.fund_price
     *
     * @mbggenerated
     */
    private BigDecimal fundPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.invest_rate
     *
     * @mbggenerated
     */
    private BigDecimal investRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.product_description
     *
     * @mbggenerated
     */
    private String productDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.risk_grade
     *
     * @mbggenerated
     */
    private String riskGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.expected__annualized_return_rate
     *
     * @mbggenerated
     */
    private BigDecimal expectedAnnualizedReturnRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.expected_profit
     *
     * @mbggenerated
     */
    private BigDecimal expectedProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.starting_nvestment_amount
     *
     * @mbggenerated
     */
    private BigDecimal startingNvestmentAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.financing_maturity
     *
     * @mbggenerated
     */
    private Integer financingMaturity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.raise_amount
     *
     * @mbggenerated
     */
    private BigDecimal raiseAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.issue_start
     *
     * @mbggenerated
     */
    private Date issueStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.issue_end
     *
     * @mbggenerated
     */
    private Date issueEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.financial_maturity_date
     *
     * @mbggenerated
     */
    private Date financialMaturityDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.latest_repayment_date
     *
     * @mbggenerated
     */
    private Date latestRepaymentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.buy_rate
     *
     * @mbggenerated
     */
    private BigDecimal buyRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.sell_rate
     *
     * @mbggenerated
     */
    private BigDecimal sellRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.issuer
     *
     * @mbggenerated
     */
    private String issuer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.issuer_id
     *
     * @mbggenerated
     */
    private String issuerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.payment_type
     *
     * @mbggenerated
     */
    private String paymentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.product_id
     *
     * @return the value of fund_info.product_id
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.product_id
     *
     * @param productId the value for fund_info.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.fund_id
     *
     * @return the value of fund_info.fund_id
     *
     * @mbggenerated
     */
    public Long getFundId() {
        return fundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.fund_id
     *
     * @param fundId the value for fund_info.fund_id
     *
     * @mbggenerated
     */
    public void setFundId(Long fundId) {
        this.fundId = fundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.fund_name
     *
     * @return the value of fund_info.fund_name
     *
     * @mbggenerated
     */
    public String getFundName() {
        return fundName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.fund_name
     *
     * @param fundName the value for fund_info.fund_name
     *
     * @mbggenerated
     */
    public void setFundName(String fundName) {
        this.fundName = fundName == null ? null : fundName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.change_rate
     *
     * @return the value of fund_info.change_rate
     *
     * @mbggenerated
     */
    public BigDecimal getChangeRate() {
        return changeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.change_rate
     *
     * @param changeRate the value for fund_info.change_rate
     *
     * @mbggenerated
     */
    public void setChangeRate(BigDecimal changeRate) {
        this.changeRate = changeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.change_price
     *
     * @return the value of fund_info.change_price
     *
     * @mbggenerated
     */
    public BigDecimal getChangePrice() {
        return changePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.change_price
     *
     * @param changePrice the value for fund_info.change_price
     *
     * @mbggenerated
     */
    public void setChangePrice(BigDecimal changePrice) {
        this.changePrice = changePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.fund_price
     *
     * @return the value of fund_info.fund_price
     *
     * @mbggenerated
     */
    public BigDecimal getFundPrice() {
        return fundPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.fund_price
     *
     * @param fundPrice the value for fund_info.fund_price
     *
     * @mbggenerated
     */
    public void setFundPrice(BigDecimal fundPrice) {
        this.fundPrice = fundPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.invest_rate
     *
     * @return the value of fund_info.invest_rate
     *
     * @mbggenerated
     */
    public BigDecimal getInvestRate() {
        return investRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.invest_rate
     *
     * @param investRate the value for fund_info.invest_rate
     *
     * @mbggenerated
     */
    public void setInvestRate(BigDecimal investRate) {
        this.investRate = investRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.product_description
     *
     * @return the value of fund_info.product_description
     *
     * @mbggenerated
     */
    public String getProductDescription() {
        return productDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.product_description
     *
     * @param productDescription the value for fund_info.product_description
     *
     * @mbggenerated
     */
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription == null ? null : productDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.risk_grade
     *
     * @return the value of fund_info.risk_grade
     *
     * @mbggenerated
     */
    public String getRiskGrade() {
        return riskGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.risk_grade
     *
     * @param riskGrade the value for fund_info.risk_grade
     *
     * @mbggenerated
     */
    public void setRiskGrade(String riskGrade) {
        this.riskGrade = riskGrade == null ? null : riskGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.expected__annualized_return_rate
     *
     * @return the value of fund_info.expected__annualized_return_rate
     *
     * @mbggenerated
     */
    public BigDecimal getExpectedAnnualizedReturnRate() {
        return expectedAnnualizedReturnRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.expected__annualized_return_rate
     *
     * @param expectedAnnualizedReturnRate the value for fund_info.expected__annualized_return_rate
     *
     * @mbggenerated
     */
    public void setExpectedAnnualizedReturnRate(BigDecimal expectedAnnualizedReturnRate) {
        this.expectedAnnualizedReturnRate = expectedAnnualizedReturnRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.expected_profit
     *
     * @return the value of fund_info.expected_profit
     *
     * @mbggenerated
     */
    public BigDecimal getExpectedProfit() {
        return expectedProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.expected_profit
     *
     * @param expectedProfit the value for fund_info.expected_profit
     *
     * @mbggenerated
     */
    public void setExpectedProfit(BigDecimal expectedProfit) {
        this.expectedProfit = expectedProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.starting_nvestment_amount
     *
     * @return the value of fund_info.starting_nvestment_amount
     *
     * @mbggenerated
     */
    public BigDecimal getStartingNvestmentAmount() {
        return startingNvestmentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.starting_nvestment_amount
     *
     * @param startingNvestmentAmount the value for fund_info.starting_nvestment_amount
     *
     * @mbggenerated
     */
    public void setStartingNvestmentAmount(BigDecimal startingNvestmentAmount) {
        this.startingNvestmentAmount = startingNvestmentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.financing_maturity
     *
     * @return the value of fund_info.financing_maturity
     *
     * @mbggenerated
     */
    public Integer getFinancingMaturity() {
        return financingMaturity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.financing_maturity
     *
     * @param financingMaturity the value for fund_info.financing_maturity
     *
     * @mbggenerated
     */
    public void setFinancingMaturity(Integer financingMaturity) {
        this.financingMaturity = financingMaturity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.raise_amount
     *
     * @return the value of fund_info.raise_amount
     *
     * @mbggenerated
     */
    public BigDecimal getRaiseAmount() {
        return raiseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.raise_amount
     *
     * @param raiseAmount the value for fund_info.raise_amount
     *
     * @mbggenerated
     */
    public void setRaiseAmount(BigDecimal raiseAmount) {
        this.raiseAmount = raiseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.issue_start
     *
     * @return the value of fund_info.issue_start
     *
     * @mbggenerated
     */
    public Date getIssueStart() {
        return issueStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.issue_start
     *
     * @param issueStart the value for fund_info.issue_start
     *
     * @mbggenerated
     */
    public void setIssueStart(Date issueStart) {
        this.issueStart = issueStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.issue_end
     *
     * @return the value of fund_info.issue_end
     *
     * @mbggenerated
     */
    public Date getIssueEnd() {
        return issueEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.issue_end
     *
     * @param issueEnd the value for fund_info.issue_end
     *
     * @mbggenerated
     */
    public void setIssueEnd(Date issueEnd) {
        this.issueEnd = issueEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.financial_maturity_date
     *
     * @return the value of fund_info.financial_maturity_date
     *
     * @mbggenerated
     */
    public Date getFinancialMaturityDate() {
        return financialMaturityDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.financial_maturity_date
     *
     * @param financialMaturityDate the value for fund_info.financial_maturity_date
     *
     * @mbggenerated
     */
    public void setFinancialMaturityDate(Date financialMaturityDate) {
        this.financialMaturityDate = financialMaturityDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.latest_repayment_date
     *
     * @return the value of fund_info.latest_repayment_date
     *
     * @mbggenerated
     */
    public Date getLatestRepaymentDate() {
        return latestRepaymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.latest_repayment_date
     *
     * @param latestRepaymentDate the value for fund_info.latest_repayment_date
     *
     * @mbggenerated
     */
    public void setLatestRepaymentDate(Date latestRepaymentDate) {
        this.latestRepaymentDate = latestRepaymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.buy_rate
     *
     * @return the value of fund_info.buy_rate
     *
     * @mbggenerated
     */
    public BigDecimal getBuyRate() {
        return buyRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.buy_rate
     *
     * @param buyRate the value for fund_info.buy_rate
     *
     * @mbggenerated
     */
    public void setBuyRate(BigDecimal buyRate) {
        this.buyRate = buyRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.sell_rate
     *
     * @return the value of fund_info.sell_rate
     *
     * @mbggenerated
     */
    public BigDecimal getSellRate() {
        return sellRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.sell_rate
     *
     * @param sellRate the value for fund_info.sell_rate
     *
     * @mbggenerated
     */
    public void setSellRate(BigDecimal sellRate) {
        this.sellRate = sellRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.issuer
     *
     * @return the value of fund_info.issuer
     *
     * @mbggenerated
     */
    public String getIssuer() {
        return issuer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.issuer
     *
     * @param issuer the value for fund_info.issuer
     *
     * @mbggenerated
     */
    public void setIssuer(String issuer) {
        this.issuer = issuer == null ? null : issuer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.issuer_id
     *
     * @return the value of fund_info.issuer_id
     *
     * @mbggenerated
     */
    public String getIssuerId() {
        return issuerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.issuer_id
     *
     * @param issuerId the value for fund_info.issuer_id
     *
     * @mbggenerated
     */
    public void setIssuerId(String issuerId) {
        this.issuerId = issuerId == null ? null : issuerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.payment_type
     *
     * @return the value of fund_info.payment_type
     *
     * @mbggenerated
     */
    public String getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.payment_type
     *
     * @param paymentType the value for fund_info.payment_type
     *
     * @mbggenerated
     */
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType == null ? null : paymentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.update_time
     *
     * @return the value of fund_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.update_time
     *
     * @param updateTime the value for fund_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_info.create_time
     *
     * @return the value of fund_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_info.create_time
     *
     * @param createTime the value for fund_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}