package org.luojj.entity;

import java.util.Date;

public class InvestmentStyleFactor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column investment_style_factor.phone_number
     *
     * @mbggenerated
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column investment_style_factor.age
     *
     * @mbggenerated
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column investment_style_factor.marital_status
     *
     * @mbggenerated
     */
    private String maritalStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column investment_style_factor.income_level
     *
     * @mbggenerated
     */
    private Integer incomeLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column investment_style_factor.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column investment_style_factor.investment_style
     *
     * @mbggenerated
     */
    private String investmentStyle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column investment_style_factor.phone_number
     *
     * @return the value of investment_style_factor.phone_number
     *
     * @mbggenerated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column investment_style_factor.phone_number
     *
     * @param phoneNumber the value for investment_style_factor.phone_number
     *
     * @mbggenerated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column investment_style_factor.age
     *
     * @return the value of investment_style_factor.age
     *
     * @mbggenerated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column investment_style_factor.age
     *
     * @param age the value for investment_style_factor.age
     *
     * @mbggenerated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column investment_style_factor.marital_status
     *
     * @return the value of investment_style_factor.marital_status
     *
     * @mbggenerated
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column investment_style_factor.marital_status
     *
     * @param maritalStatus the value for investment_style_factor.marital_status
     *
     * @mbggenerated
     */
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus == null ? null : maritalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column investment_style_factor.income_level
     *
     * @return the value of investment_style_factor.income_level
     *
     * @mbggenerated
     */
    public Integer getIncomeLevel() {
        return incomeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column investment_style_factor.income_level
     *
     * @param incomeLevel the value for investment_style_factor.income_level
     *
     * @mbggenerated
     */
    public void setIncomeLevel(Integer incomeLevel) {
        this.incomeLevel = incomeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column investment_style_factor.create_time
     *
     * @return the value of investment_style_factor.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column investment_style_factor.create_time
     *
     * @param createTime the value for investment_style_factor.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column investment_style_factor.investment_style
     *
     * @return the value of investment_style_factor.investment_style
     *
     * @mbggenerated
     */
    public String getInvestmentStyle() {
        return investmentStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column investment_style_factor.investment_style
     *
     * @param investmentStyle the value for investment_style_factor.investment_style
     *
     * @mbggenerated
     */
    public void setInvestmentStyle(String investmentStyle) {
        this.investmentStyle = investmentStyle == null ? null : investmentStyle.trim();
    }
}