package org.luojj.entity;

import java.math.BigDecimal;
import java.util.Date;

public class InvestGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest_group.invest_group_id
     *
     * @mbggenerated
     */
    private Long investGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest_group.is_recommend
     *
     * @mbggenerated
     */
    private Integer isRecommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest_group.phone_number
     *
     * @mbggenerated
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest_group.product_id
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest_group.high_risk_id
     *
     * @mbggenerated
     */
    private Long highRiskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest_group.middle_risk_id
     *
     * @mbggenerated
     */
    private Long middleRiskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest_group.low_risk_id
     *
     * @mbggenerated
     */
    private Long lowRiskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest_group.duration
     *
     * @mbggenerated
     */
    private Integer duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest_group.group_rate
     *
     * @mbggenerated
     */
    private BigDecimal groupRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest_group.group_profit
     *
     * @mbggenerated
     */
    private BigDecimal groupProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invest_group.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest_group.invest_group_id
     *
     * @return the value of invest_group.invest_group_id
     *
     * @mbggenerated
     */
    public Long getInvestGroupId() {
        return investGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest_group.invest_group_id
     *
     * @param investGroupId the value for invest_group.invest_group_id
     *
     * @mbggenerated
     */
    public void setInvestGroupId(Long investGroupId) {
        this.investGroupId = investGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest_group.is_recommend
     *
     * @return the value of invest_group.is_recommend
     *
     * @mbggenerated
     */
    public Integer getIsRecommend() {
        return isRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest_group.is_recommend
     *
     * @param isRecommend the value for invest_group.is_recommend
     *
     * @mbggenerated
     */
    public void setIsRecommend(Integer isRecommend) {
        this.isRecommend = isRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest_group.phone_number
     *
     * @return the value of invest_group.phone_number
     *
     * @mbggenerated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest_group.phone_number
     *
     * @param phoneNumber the value for invest_group.phone_number
     *
     * @mbggenerated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest_group.product_id
     *
     * @return the value of invest_group.product_id
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest_group.product_id
     *
     * @param productId the value for invest_group.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest_group.high_risk_id
     *
     * @return the value of invest_group.high_risk_id
     *
     * @mbggenerated
     */
    public Long getHighRiskId() {
        return highRiskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest_group.high_risk_id
     *
     * @param highRiskId the value for invest_group.high_risk_id
     *
     * @mbggenerated
     */
    public void setHighRiskId(Long highRiskId) {
        this.highRiskId = highRiskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest_group.middle_risk_id
     *
     * @return the value of invest_group.middle_risk_id
     *
     * @mbggenerated
     */
    public Long getMiddleRiskId() {
        return middleRiskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest_group.middle_risk_id
     *
     * @param middleRiskId the value for invest_group.middle_risk_id
     *
     * @mbggenerated
     */
    public void setMiddleRiskId(Long middleRiskId) {
        this.middleRiskId = middleRiskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest_group.low_risk_id
     *
     * @return the value of invest_group.low_risk_id
     *
     * @mbggenerated
     */
    public Long getLowRiskId() {
        return lowRiskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest_group.low_risk_id
     *
     * @param lowRiskId the value for invest_group.low_risk_id
     *
     * @mbggenerated
     */
    public void setLowRiskId(Long lowRiskId) {
        this.lowRiskId = lowRiskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest_group.duration
     *
     * @return the value of invest_group.duration
     *
     * @mbggenerated
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest_group.duration
     *
     * @param duration the value for invest_group.duration
     *
     * @mbggenerated
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest_group.group_rate
     *
     * @return the value of invest_group.group_rate
     *
     * @mbggenerated
     */
    public BigDecimal getGroupRate() {
        return groupRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest_group.group_rate
     *
     * @param groupRate the value for invest_group.group_rate
     *
     * @mbggenerated
     */
    public void setGroupRate(BigDecimal groupRate) {
        this.groupRate = groupRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest_group.group_profit
     *
     * @return the value of invest_group.group_profit
     *
     * @mbggenerated
     */
    public BigDecimal getGroupProfit() {
        return groupProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest_group.group_profit
     *
     * @param groupProfit the value for invest_group.group_profit
     *
     * @mbggenerated
     */
    public void setGroupProfit(BigDecimal groupProfit) {
        this.groupProfit = groupProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invest_group.create_time
     *
     * @return the value of invest_group.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invest_group.create_time
     *
     * @param createTime the value for invest_group.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}