package org.luojj.entity;

import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonSerialize;
import org.luojj.baseclass.BaseBean;
import org.luojj.util.CustomDateSerializer;

public class MessageCenter extends BaseBean{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_info.msg_id
     *
     * @mbggenerated
     */
    private Long msgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_info.phone_number
     *
     * @mbggenerated
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_info.msg_content
     *
     * @mbggenerated
     */
    private String msgContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_info.msg_id
     *
     * @return the value of message_info.msg_id
     *
     * @mbggenerated
     */
    public Long getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_info.msg_id
     *
     * @param msgId the value for message_info.msg_id
     *
     * @mbggenerated
     */
    public void setMsgId(Long msgId) {
        this.msgId = msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_info.phone_number
     *
     * @return the value of message_info.phone_number
     *
     * @mbggenerated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_info.phone_number
     *
     * @param phoneNumber the value for message_info.phone_number
     *
     * @mbggenerated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_info.msg_content
     *
     * @return the value of message_info.msg_content
     *
     * @mbggenerated
     */
    public String getMsgContent() {
        return msgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_info.msg_content
     *
     * @param msgContent the value for message_info.msg_content
     *
     * @mbggenerated
     */
    public void setMsgContent(String msgContent) {
        this.msgContent = msgContent == null ? null : msgContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_info.create_time
     *
     * @return the value of message_info.create_time
     *
     * @mbggenerated
     */
    @JsonSerialize(using = CustomDateSerializer.class)  
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_info.create_time
     *
     * @param createTime the value for message_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}