package org.luojj.entity;

import java.math.BigDecimal;
import java.util.Date;

public class OrderDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.product_id
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.quantity
     *
     * @mbggenerated
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.yesterday_profit
     *
     * @mbggenerated
     */
    private BigDecimal yesterdayProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.expected_profit
     *
     * @mbggenerated
     */
    private BigDecimal expectedProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.unit_price
     *
     * @mbggenerated
     */
    private BigDecimal unitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.product_id
     *
     * @return the value of order_detail.product_id
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.product_id
     *
     * @param productId the value for order_detail.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.order_id
     *
     * @return the value of order_detail.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.order_id
     *
     * @param orderId the value for order_detail.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.quantity
     *
     * @return the value of order_detail.quantity
     *
     * @mbggenerated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.quantity
     *
     * @param quantity the value for order_detail.quantity
     *
     * @mbggenerated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.yesterday_profit
     *
     * @return the value of order_detail.yesterday_profit
     *
     * @mbggenerated
     */
    public BigDecimal getYesterdayProfit() {
        return yesterdayProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.yesterday_profit
     *
     * @param yesterdayProfit the value for order_detail.yesterday_profit
     *
     * @mbggenerated
     */
    public void setYesterdayProfit(BigDecimal yesterdayProfit) {
        this.yesterdayProfit = yesterdayProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.expected_profit
     *
     * @return the value of order_detail.expected_profit
     *
     * @mbggenerated
     */
    public BigDecimal getExpectedProfit() {
        return expectedProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.expected_profit
     *
     * @param expectedProfit the value for order_detail.expected_profit
     *
     * @mbggenerated
     */
    public void setExpectedProfit(BigDecimal expectedProfit) {
        this.expectedProfit = expectedProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.unit_price
     *
     * @return the value of order_detail.unit_price
     *
     * @mbggenerated
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.unit_price
     *
     * @param unitPrice the value for order_detail.unit_price
     *
     * @mbggenerated
     */
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.create_time
     *
     * @return the value of order_detail.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.create_time
     *
     * @param createTime the value for order_detail.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}