package org.luojj.entity;

import java.math.BigDecimal;
import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonSerialize;
import org.luojj.util.CustomDateSerializer;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.phone_number
     *
     * @mbggenerated
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_description
     *
     * @mbggenerated
     */
    private String orderDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_amount
     *
     * @mbggenerated
     */
    private BigDecimal orderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_status
     *
     * @mbggenerated
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.actual_amount
     *
     * @mbggenerated
     */
    private BigDecimal actualAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.payment_type
     *
     * @mbggenerated
     */
    private String paymentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.payment_type_content
     *
     * @mbggenerated
     */
    private String paymentTypeContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_failure_time
     *
     * @mbggenerated
     */
    private Date orderFailureTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.invest_group_id
     *
     * @mbggenerated
     */
    private Long investGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.yesterday_profit
     *
     * @mbggenerated
     */
    private BigDecimal yesterdayProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.total_profit
     *
     * @mbggenerated
     */
    private BigDecimal totalProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_rate
     *
     * @mbggenerated
     */
    private BigDecimal orderRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.expected_profit
     *
     * @mbggenerated
     */
    private BigDecimal expectedProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.last_update_time
     *
     * @mbggenerated
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.is_valid
     *
     * @mbggenerated
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_id
     *
     * @return the value of order_info.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_id
     *
     * @param orderId the value for order_info.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.phone_number
     *
     * @return the value of order_info.phone_number
     *
     * @mbggenerated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.phone_number
     *
     * @param phoneNumber the value for order_info.phone_number
     *
     * @mbggenerated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_description
     *
     * @return the value of order_info.order_description
     *
     * @mbggenerated
     */
    public String getOrderDescription() {
        return orderDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_description
     *
     * @param orderDescription the value for order_info.order_description
     *
     * @mbggenerated
     */
    public void setOrderDescription(String orderDescription) {
        this.orderDescription = orderDescription == null ? null : orderDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_amount
     *
     * @return the value of order_info.order_amount
     *
     * @mbggenerated
     */
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_amount
     *
     * @param orderAmount the value for order_info.order_amount
     *
     * @mbggenerated
     */
    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_status
     *
     * @return the value of order_info.order_status
     *
     * @mbggenerated
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_status
     *
     * @param orderStatus the value for order_info.order_status
     *
     * @mbggenerated
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.actual_amount
     *
     * @return the value of order_info.actual_amount
     *
     * @mbggenerated
     */
    public BigDecimal getActualAmount() {
        return actualAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.actual_amount
     *
     * @param actualAmount the value for order_info.actual_amount
     *
     * @mbggenerated
     */
    public void setActualAmount(BigDecimal actualAmount) {
        this.actualAmount = actualAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.payment_type
     *
     * @return the value of order_info.payment_type
     *
     * @mbggenerated
     */
    public String getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.payment_type
     *
     * @param paymentType the value for order_info.payment_type
     *
     * @mbggenerated
     */
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType == null ? null : paymentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.payment_type_content
     *
     * @return the value of order_info.payment_type_content
     *
     * @mbggenerated
     */
    public String getPaymentTypeContent() {
        return paymentTypeContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.payment_type_content
     *
     * @param paymentTypeContent the value for order_info.payment_type_content
     *
     * @mbggenerated
     */
    public void setPaymentTypeContent(String paymentTypeContent) {
        this.paymentTypeContent = paymentTypeContent == null ? null : paymentTypeContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_failure_time
     *
     * @return the value of order_info.order_failure_time
     *
     * @mbggenerated
     */
    public Date getOrderFailureTime() {
        return orderFailureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_failure_time
     *
     * @param orderFailureTime the value for order_info.order_failure_time
     *
     * @mbggenerated
     */
    public void setOrderFailureTime(Date orderFailureTime) {
        this.orderFailureTime = orderFailureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.invest_group_id
     *
     * @return the value of order_info.invest_group_id
     *
     * @mbggenerated
     */
    public Long getInvestGroupId() {
        return investGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.invest_group_id
     *
     * @param investGroupId the value for order_info.invest_group_id
     *
     * @mbggenerated
     */
    public void setInvestGroupId(Long investGroupId) {
        this.investGroupId = investGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.yesterday_profit
     *
     * @return the value of order_info.yesterday_profit
     *
     * @mbggenerated
     */
    public BigDecimal getYesterdayProfit() {
        return yesterdayProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.yesterday_profit
     *
     * @param yesterdayProfit the value for order_info.yesterday_profit
     *
     * @mbggenerated
     */
    public void setYesterdayProfit(BigDecimal yesterdayProfit) {
        this.yesterdayProfit = yesterdayProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.total_profit
     *
     * @return the value of order_info.total_profit
     *
     * @mbggenerated
     */
    public BigDecimal getTotalProfit() {
        return totalProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.total_profit
     *
     * @param totalProfit the value for order_info.total_profit
     *
     * @mbggenerated
     */
    public void setTotalProfit(BigDecimal totalProfit) {
        this.totalProfit = totalProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_rate
     *
     * @return the value of order_info.order_rate
     *
     * @mbggenerated
     */
    public BigDecimal getOrderRate() {
        return orderRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_rate
     *
     * @param orderRate the value for order_info.order_rate
     *
     * @mbggenerated
     */
    public void setOrderRate(BigDecimal orderRate) {
        this.orderRate = orderRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.expected_profit
     *
     * @return the value of order_info.expected_profit
     *
     * @mbggenerated
     */
    public BigDecimal getExpectedProfit() {
        return expectedProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.expected_profit
     *
     * @param expectedProfit the value for order_info.expected_profit
     *
     * @mbggenerated
     */
    public void setExpectedProfit(BigDecimal expectedProfit) {
        this.expectedProfit = expectedProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.last_update_time
     *
     * @return the value of order_info.last_update_time
     *
     * @mbggenerated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.last_update_time
     *
     * @param lastUpdateTime the value for order_info.last_update_time
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.is_valid
     *
     * @return the value of order_info.is_valid
     *
     * @mbggenerated
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.is_valid
     *
     * @param isValid the value for order_info.is_valid
     *
     * @mbggenerated
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.create_time
     *
     * @return the value of order_info.create_time
     *
     * @mbggenerated
     */
    @JsonSerialize(using = CustomDateSerializer.class)  
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.create_time
     *
     * @param createTime the value for order_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}