package org.luojj.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_id
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.financing_amount
     *
     * @mbggenerated
     */
    private BigDecimal financingAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.expected__annualized_return_rate
     *
     * @mbggenerated
     */
    private BigDecimal expectedAnnualizedReturnRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.front_annualized_return_rate
     *
     * @mbggenerated
     */
    private BigDecimal frontAnnualizedReturnRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.starting_nvestment_amount
     *
     * @mbggenerated
     */
    private BigDecimal startingNvestmentAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.financing_maturity
     *
     * @mbggenerated
     */
    private Integer financingMaturity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.raise_amount
     *
     * @mbggenerated
     */
    private BigDecimal raiseAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.issue_start
     *
     * @mbggenerated
     */
    private Date issueStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.issue_end
     *
     * @mbggenerated
     */
    private Date issueEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.financial_maturity_date
     *
     * @mbggenerated
     */
    private Date financialMaturityDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.latest_repayment_date
     *
     * @mbggenerated
     */
    private Date latestRepaymentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.purchase_fund_amount
     *
     * @mbggenerated
     */
    private BigDecimal purchaseFundAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.residual_purchase_amount
     *
     * @mbggenerated
     */
    private BigDecimal residualPurchaseAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.issuer
     *
     * @mbggenerated
     */
    private String issuer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.issuer_pin
     *
     * @mbggenerated
     */
    private String issuerPin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.payment_type
     *
     * @mbggenerated
     */
    private String paymentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.merchant_number
     *
     * @mbggenerated
     */
    private String merchantNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_description
     *
     * @mbggenerated
     */
    private String productDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_id
     *
     * @return the value of product_info.product_id
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_id
     *
     * @param productId the value for product_info.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_name
     *
     * @return the value of product_info.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_name
     *
     * @param productName the value for product_info.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.financing_amount
     *
     * @return the value of product_info.financing_amount
     *
     * @mbggenerated
     */
    public BigDecimal getFinancingAmount() {
        return financingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.financing_amount
     *
     * @param financingAmount the value for product_info.financing_amount
     *
     * @mbggenerated
     */
    public void setFinancingAmount(BigDecimal financingAmount) {
        this.financingAmount = financingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.expected__annualized_return_rate
     *
     * @return the value of product_info.expected__annualized_return_rate
     *
     * @mbggenerated
     */
    public BigDecimal getExpectedAnnualizedReturnRate() {
        return expectedAnnualizedReturnRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.expected__annualized_return_rate
     *
     * @param expectedAnnualizedReturnRate the value for product_info.expected__annualized_return_rate
     *
     * @mbggenerated
     */
    public void setExpectedAnnualizedReturnRate(BigDecimal expectedAnnualizedReturnRate) {
        this.expectedAnnualizedReturnRate = expectedAnnualizedReturnRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.front_annualized_return_rate
     *
     * @return the value of product_info.front_annualized_return_rate
     *
     * @mbggenerated
     */
    public BigDecimal getFrontAnnualizedReturnRate() {
        return frontAnnualizedReturnRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.front_annualized_return_rate
     *
     * @param frontAnnualizedReturnRate the value for product_info.front_annualized_return_rate
     *
     * @mbggenerated
     */
    public void setFrontAnnualizedReturnRate(BigDecimal frontAnnualizedReturnRate) {
        this.frontAnnualizedReturnRate = frontAnnualizedReturnRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.starting_nvestment_amount
     *
     * @return the value of product_info.starting_nvestment_amount
     *
     * @mbggenerated
     */
    public BigDecimal getStartingNvestmentAmount() {
        return startingNvestmentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.starting_nvestment_amount
     *
     * @param startingNvestmentAmount the value for product_info.starting_nvestment_amount
     *
     * @mbggenerated
     */
    public void setStartingNvestmentAmount(BigDecimal startingNvestmentAmount) {
        this.startingNvestmentAmount = startingNvestmentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.financing_maturity
     *
     * @return the value of product_info.financing_maturity
     *
     * @mbggenerated
     */
    public Integer getFinancingMaturity() {
        return financingMaturity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.financing_maturity
     *
     * @param financingMaturity the value for product_info.financing_maturity
     *
     * @mbggenerated
     */
    public void setFinancingMaturity(Integer financingMaturity) {
        this.financingMaturity = financingMaturity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.raise_amount
     *
     * @return the value of product_info.raise_amount
     *
     * @mbggenerated
     */
    public BigDecimal getRaiseAmount() {
        return raiseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.raise_amount
     *
     * @param raiseAmount the value for product_info.raise_amount
     *
     * @mbggenerated
     */
    public void setRaiseAmount(BigDecimal raiseAmount) {
        this.raiseAmount = raiseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.issue_start
     *
     * @return the value of product_info.issue_start
     *
     * @mbggenerated
     */
    public Date getIssueStart() {
        return issueStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.issue_start
     *
     * @param issueStart the value for product_info.issue_start
     *
     * @mbggenerated
     */
    public void setIssueStart(Date issueStart) {
        this.issueStart = issueStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.issue_end
     *
     * @return the value of product_info.issue_end
     *
     * @mbggenerated
     */
    public Date getIssueEnd() {
        return issueEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.issue_end
     *
     * @param issueEnd the value for product_info.issue_end
     *
     * @mbggenerated
     */
    public void setIssueEnd(Date issueEnd) {
        this.issueEnd = issueEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.financial_maturity_date
     *
     * @return the value of product_info.financial_maturity_date
     *
     * @mbggenerated
     */
    public Date getFinancialMaturityDate() {
        return financialMaturityDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.financial_maturity_date
     *
     * @param financialMaturityDate the value for product_info.financial_maturity_date
     *
     * @mbggenerated
     */
    public void setFinancialMaturityDate(Date financialMaturityDate) {
        this.financialMaturityDate = financialMaturityDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.latest_repayment_date
     *
     * @return the value of product_info.latest_repayment_date
     *
     * @mbggenerated
     */
    public Date getLatestRepaymentDate() {
        return latestRepaymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.latest_repayment_date
     *
     * @param latestRepaymentDate the value for product_info.latest_repayment_date
     *
     * @mbggenerated
     */
    public void setLatestRepaymentDate(Date latestRepaymentDate) {
        this.latestRepaymentDate = latestRepaymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.purchase_fund_amount
     *
     * @return the value of product_info.purchase_fund_amount
     *
     * @mbggenerated
     */
    public BigDecimal getPurchaseFundAmount() {
        return purchaseFundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.purchase_fund_amount
     *
     * @param purchaseFundAmount the value for product_info.purchase_fund_amount
     *
     * @mbggenerated
     */
    public void setPurchaseFundAmount(BigDecimal purchaseFundAmount) {
        this.purchaseFundAmount = purchaseFundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.residual_purchase_amount
     *
     * @return the value of product_info.residual_purchase_amount
     *
     * @mbggenerated
     */
    public BigDecimal getResidualPurchaseAmount() {
        return residualPurchaseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.residual_purchase_amount
     *
     * @param residualPurchaseAmount the value for product_info.residual_purchase_amount
     *
     * @mbggenerated
     */
    public void setResidualPurchaseAmount(BigDecimal residualPurchaseAmount) {
        this.residualPurchaseAmount = residualPurchaseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.issuer
     *
     * @return the value of product_info.issuer
     *
     * @mbggenerated
     */
    public String getIssuer() {
        return issuer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.issuer
     *
     * @param issuer the value for product_info.issuer
     *
     * @mbggenerated
     */
    public void setIssuer(String issuer) {
        this.issuer = issuer == null ? null : issuer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.issuer_pin
     *
     * @return the value of product_info.issuer_pin
     *
     * @mbggenerated
     */
    public String getIssuerPin() {
        return issuerPin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.issuer_pin
     *
     * @param issuerPin the value for product_info.issuer_pin
     *
     * @mbggenerated
     */
    public void setIssuerPin(String issuerPin) {
        this.issuerPin = issuerPin == null ? null : issuerPin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.payment_type
     *
     * @return the value of product_info.payment_type
     *
     * @mbggenerated
     */
    public String getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.payment_type
     *
     * @param paymentType the value for product_info.payment_type
     *
     * @mbggenerated
     */
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType == null ? null : paymentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.merchant_number
     *
     * @return the value of product_info.merchant_number
     *
     * @mbggenerated
     */
    public String getMerchantNumber() {
        return merchantNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.merchant_number
     *
     * @param merchantNumber the value for product_info.merchant_number
     *
     * @mbggenerated
     */
    public void setMerchantNumber(String merchantNumber) {
        this.merchantNumber = merchantNumber == null ? null : merchantNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.modify_time
     *
     * @return the value of product_info.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.modify_time
     *
     * @param modifyTime the value for product_info.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.create_time
     *
     * @return the value of product_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.create_time
     *
     * @param createTime the value for product_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_description
     *
     * @return the value of product_info.product_description
     *
     * @mbggenerated
     */
    public String getProductDescription() {
        return productDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_description
     *
     * @param productDescription the value for product_info.product_description
     *
     * @mbggenerated
     */
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription == null ? null : productDescription.trim();
    }
}