package org.luojj.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Stock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.product_id
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.stock_id
     *
     * @mbggenerated
     */
    private Integer stockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.stock_code
     *
     * @mbggenerated
     */
    private String stockCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.stock_name
     *
     * @mbggenerated
     */
    private String stockName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.stock_type
     *
     * @mbggenerated
     */
    private String stockType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.stock_price
     *
     * @mbggenerated
     */
    private BigDecimal stockPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.change_rate
     *
     * @mbggenerated
     */
    private BigDecimal changeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.change_price
     *
     * @mbggenerated
     */
    private BigDecimal changePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.buy_base
     *
     * @mbggenerated
     */
    private Integer buyBase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.buy_rate
     *
     * @mbggenerated
     */
    private BigDecimal buyRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.sell_rate
     *
     * @mbggenerated
     */
    private BigDecimal sellRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.product_id
     *
     * @return the value of stock_info.product_id
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.product_id
     *
     * @param productId the value for stock_info.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.stock_id
     *
     * @return the value of stock_info.stock_id
     *
     * @mbggenerated
     */
    public Integer getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.stock_id
     *
     * @param stockId the value for stock_info.stock_id
     *
     * @mbggenerated
     */
    public void setStockId(Integer stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.stock_code
     *
     * @return the value of stock_info.stock_code
     *
     * @mbggenerated
     */
    public String getStockCode() {
        return stockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.stock_code
     *
     * @param stockCode the value for stock_info.stock_code
     *
     * @mbggenerated
     */
    public void setStockCode(String stockCode) {
        this.stockCode = stockCode == null ? null : stockCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.stock_name
     *
     * @return the value of stock_info.stock_name
     *
     * @mbggenerated
     */
    public String getStockName() {
        return stockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.stock_name
     *
     * @param stockName the value for stock_info.stock_name
     *
     * @mbggenerated
     */
    public void setStockName(String stockName) {
        this.stockName = stockName == null ? null : stockName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.stock_type
     *
     * @return the value of stock_info.stock_type
     *
     * @mbggenerated
     */
    public String getStockType() {
        return stockType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.stock_type
     *
     * @param stockType the value for stock_info.stock_type
     *
     * @mbggenerated
     */
    public void setStockType(String stockType) {
        this.stockType = stockType == null ? null : stockType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.stock_price
     *
     * @return the value of stock_info.stock_price
     *
     * @mbggenerated
     */
    public BigDecimal getStockPrice() {
        return stockPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.stock_price
     *
     * @param stockPrice the value for stock_info.stock_price
     *
     * @mbggenerated
     */
    public void setStockPrice(BigDecimal stockPrice) {
        this.stockPrice = stockPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.change_rate
     *
     * @return the value of stock_info.change_rate
     *
     * @mbggenerated
     */
    public BigDecimal getChangeRate() {
        return changeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.change_rate
     *
     * @param changeRate the value for stock_info.change_rate
     *
     * @mbggenerated
     */
    public void setChangeRate(BigDecimal changeRate) {
        this.changeRate = changeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.change_price
     *
     * @return the value of stock_info.change_price
     *
     * @mbggenerated
     */
    public BigDecimal getChangePrice() {
        return changePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.change_price
     *
     * @param changePrice the value for stock_info.change_price
     *
     * @mbggenerated
     */
    public void setChangePrice(BigDecimal changePrice) {
        this.changePrice = changePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.buy_base
     *
     * @return the value of stock_info.buy_base
     *
     * @mbggenerated
     */
    public Integer getBuyBase() {
        return buyBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.buy_base
     *
     * @param buyBase the value for stock_info.buy_base
     *
     * @mbggenerated
     */
    public void setBuyBase(Integer buyBase) {
        this.buyBase = buyBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.buy_rate
     *
     * @return the value of stock_info.buy_rate
     *
     * @mbggenerated
     */
    public BigDecimal getBuyRate() {
        return buyRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.buy_rate
     *
     * @param buyRate the value for stock_info.buy_rate
     *
     * @mbggenerated
     */
    public void setBuyRate(BigDecimal buyRate) {
        this.buyRate = buyRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.sell_rate
     *
     * @return the value of stock_info.sell_rate
     *
     * @mbggenerated
     */
    public BigDecimal getSellRate() {
        return sellRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.sell_rate
     *
     * @param sellRate the value for stock_info.sell_rate
     *
     * @mbggenerated
     */
    public void setSellRate(BigDecimal sellRate) {
        this.sellRate = sellRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.update_time
     *
     * @return the value of stock_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.update_time
     *
     * @param updateTime the value for stock_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.create_time
     *
     * @return the value of stock_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.create_time
     *
     * @param createTime the value for stock_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}