package org.luojj.entity;

import java.math.BigDecimal;
import java.util.Date;

import org.luojj.baseclass.BaseBean;

public class TradingRecord extends BaseBean{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_record.trading_record_id
     *
     * @mbggenerated
     */
    private Long tradingRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_record.phone_number
     *
     * @mbggenerated
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_record.trading_type
     *
     * @mbggenerated
     */
    private String tradingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_record.trading_amount
     *
     * @mbggenerated
     */
    private BigDecimal tradingAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_record.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_record.payment_type
     *
     * @mbggenerated
     */
    private String paymentType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_record.trading_record_id
     *
     * @return the value of trading_record.trading_record_id
     *
     * @mbggenerated
     */
    public Long getTradingRecordId() {
        return tradingRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_record.trading_record_id
     *
     * @param tradingRecordId the value for trading_record.trading_record_id
     *
     * @mbggenerated
     */
    public void setTradingRecordId(Long tradingRecordId) {
        this.tradingRecordId = tradingRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_record.phone_number
     *
     * @return the value of trading_record.phone_number
     *
     * @mbggenerated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_record.phone_number
     *
     * @param phoneNumber the value for trading_record.phone_number
     *
     * @mbggenerated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_record.trading_type
     *
     * @return the value of trading_record.trading_type
     *
     * @mbggenerated
     */
    public String getTradingType() {
        return tradingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_record.trading_type
     *
     * @param tradingType the value for trading_record.trading_type
     *
     * @mbggenerated
     */
    public void setTradingType(String tradingType) {
        this.tradingType = tradingType == null ? null : tradingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_record.trading_amount
     *
     * @return the value of trading_record.trading_amount
     *
     * @mbggenerated
     */
    public BigDecimal getTradingAmount() {
        return tradingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_record.trading_amount
     *
     * @param tradingAmount the value for trading_record.trading_amount
     *
     * @mbggenerated
     */
    public void setTradingAmount(BigDecimal tradingAmount) {
        this.tradingAmount = tradingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_record.create_time
     *
     * @return the value of trading_record.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_record.create_time
     *
     * @param createTime the value for trading_record.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_record.payment_type
     *
     * @return the value of trading_record.payment_type
     *
     * @mbggenerated
     */
    public String getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_record.payment_type
     *
     * @param paymentType the value for trading_record.payment_type
     *
     * @mbggenerated
     */
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType == null ? null : paymentType.trim();
    }
}